apiVersion: v1
kind: Service
metadata:
  name: hello
  labels:
    app: hello
    track: canary
spec:
  type: NodePort
  selector:
    app: hello
    track: canary
  ports:
  - name: http
    nodePort: 37000
    port: 80
    protocol: TCP
