apiVersion: v1
kind: Service
metadata:
  name: hello-v1
  labels:
    app: hello
    version: 1.0.0
spec:
  type: NodePort
  selector:
    app: hello
    version: 1.0.0
  ports:
  - name: http
    nodePort: 36001
    port: 80
    protocol: TCP
