apiVersion: v1
kind: Service
metadata:
  name: hello-stable
  labels:
    app: hello
    track: stable
spec:
  type: LoadBalancer
  selector:
    app: hello
    track: stable
  ports:
  - name: http
    port: 80
    protocol: TCP
