apiVersion: v1
kind: Service
metadata:
  name: hello-v2
  labels:
    app: hello
    version: 2.0.0
spec:
  type: NodePort
  selector:
    app: hello
    version: 2.0.0
  ports:
  - name: http
    nodePort: 36002
    port: 80
    protocol: TCP
