apiVersion: v1
kind: Service
metadata:
  name: hello-canary
  labels:
    app: hello
    track: canary
spec:
  type: LoadBalancer
  selector:
    app: hello
    track: canary
  ports:
  - name: http
    port: 80
    protocol: TCP
